{"nick":"yhwang_","reason":"Ping timeout: 240 seconds","date":"2018-02-28T00:03:13.286Z","type":"quit"}
{"nick":"node-gh","date":"2018-02-28T00:07:52.806Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:07:52.806Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T00:11:01.325Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:11:01.326Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T00:12:00.095Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:12:00.164Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T00:14:44.142Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:14:44.289Z","type":"part"}
{"nick":"yhwang_","date":"2018-02-28T00:15:39.150Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:32:51.855Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:32:51.962Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T00:33:55.565Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:33:55.633Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T00:44:22.152Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:44:22.222Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T00:50:18.123Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T00:50:18.190Z","type":"part"}
{"nick":"rvagg","message":"Trott, mhdawson: here's an interesting case: https://ci.nodejs.org/job/node-test-commit-linux-containered/2544/nodes=ubuntu1604_sharedlibs_openssl110_x64/ - that specific docker container has failed twice in a row but on different tests and for different uses. This test is some random \"CRASHED\" while testing OpenSSL 1.1.0. The previous was a seemingly random timeout on a different test while doing FIPS testing","date":"2018-02-28T00:54:43.930Z","type":"message"}
{"nick":"rvagg","message":"Trott, mhdawson:  It says to me there's something wrong inside the container or on the machine, something about resources. _BUT_ I can't find anything wrong. I hop into the parent machine and it looks normal, no zombies, nothing hogging resources. I hope _into_ the container and there's nothing but `java` running in there. It's these cases where I have zero idea of what might be up but it looks like it's the fault of","date":"2018-02-28T00:55:38.479Z","type":"message"}
{"nick":"rvagg","message":"the machine.. Might just need to reboot..","date":"2018-02-28T00:55:38.479Z","type":"message"}
{"nick":"rvagg","message":"also, I have no idea what to do about this kind of failure https://ci.nodejs.org/job/node-test-commit-linux/16720/nodes=centos6-64/console","date":"2018-02-28T01:00:18.654Z","type":"message"}
{"nick":"rvagg","message":"maybe upgrade git, but I'd just be stabbing in the dark on that .. it's the only failure for that node-test-commit run so it's not GitHub's fault","date":"2018-02-28T01:00:45.744Z","type":"message"}
{"nick":"node-gh","date":"2018-02-28T01:00:53.451Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T01:00:53.519Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T01:05:54.281Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T01:05:54.349Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T01:06:48.438Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T01:06:48.506Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T01:06:58.049Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T01:06:58.117Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T01:07:05.016Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T01:07:05.160Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T01:35:59.438Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T01:35:59.506Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T02:28:41.420Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T02:28:41.526Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T02:51:01.162Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T02:51:01.308Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T02:56:56.057Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T02:56:56.126Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:00:13.907Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:00:13.975Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:07:13.854Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:07:13.923Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:10:50.140Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:10:50.246Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:11:03.121Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:11:03.190Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:20:30.145Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:20:30.252Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:24:59.063Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:24:59.131Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:26:14.595Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:26:14.702Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:52:11.170Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:52:11.170Z","type":"part"}
{"nick":"node-gh","date":"2018-02-28T03:56:01.426Z","type":"join"}
{"nick":"node-gh","date":"2018-02-28T03:56:01.495Z","type":"part"}
{"nick":"BridgeAR","reason":"Ping timeout: 260 seconds","date":"2018-02-28T04:06:04.950Z","type":"quit"}
{"nick":"rvagg","message":"did someone run ansible on test-digitalocean-ubuntu1204-x64-1? it had the wrong secret in it, someone must have had an old host_vars from before its rename","date":"2018-02-28T06:13:56.886Z","type":"message"}
{"nick":"seishun","date":"2018-02-28T07:49:16.754Z","type":"join"}
