{"nick":"Roughy","reason":"Ping timeout: 268 seconds","date":"2018-05-08T00:50:19.802Z","type":"quit"}
{"nick":"Roughy","date":"2018-05-08T00:51:02.178Z","type":"join"}
{"nick":"leolove","reason":"Quit: This computer has gone to sleep","date":"2018-05-08T01:28:26.459Z","type":"quit"}
{"nick":"Roughy","reason":"Ping timeout: 264 seconds","date":"2018-05-08T01:31:33.968Z","type":"quit"}
{"nick":"Roughy","date":"2018-05-08T01:35:33.148Z","type":"join"}
{"nick":"Guest67487","date":"2018-05-08T02:07:10.385Z","type":"join"}
{"nick":"Guest67487","message":"So, I have a routine that throws an exception within an app.use(path, function(req, res, next){}) method.  is there a way of making that error appear, or do I have to wrap everything inside of the app.use with a try/catch to be sure it's not throwing an error that won't be seen?","date":"2018-05-08T02:08:24.520Z","type":"message"}
{"nick":"Guest67487","reason":"Quit: Leaving","date":"2018-05-08T02:30:08.623Z","type":"quit"}
{"nick":"TrentonAdams","date":"2018-05-08T02:30:38.183Z","type":"join"}
{"nick":"jgornick","reason":"Ping timeout: 240 seconds","date":"2018-05-08T03:05:51.418Z","type":"quit"}
{"nick":"Roughy","reason":"Quit: Meadow Fresh milk","date":"2018-05-08T03:21:46.020Z","type":"quit"}
{"nick":"Arcarc","date":"2018-05-08T03:43:11.474Z","type":"join"}
{"nick":"TrentonAdams","message":"I was in as guest earlier apparently.  So, I have a routine that throws an exception within an app.use(path, function(req, res, next){}) method.  is there a way of making that error appear, or do I have to wrap everything inside of the app.use with a try/catch to be sure it's not throwing an error that won't be seen?","date":"2018-05-08T03:43:17.409Z","type":"message"}
{"nick":"chovy","reason":"Quit: leaving","date":"2018-05-08T05:21:03.442Z","type":"quit"}
{"nick":"Jitu","date":"2018-05-08T06:34:48.965Z","type":"join"}
{"nick":"Jitu","message":"Hi","date":"2018-05-08T06:34:58.634Z","type":"message"}
{"nick":"Jitu","message":"what is path","date":"2018-05-08T06:35:17.464Z","type":"message"}
{"nick":"Jitu","message":"in nodejs","date":"2018-05-08T06:35:32.479Z","type":"message"}
{"nick":"Jitu","message":"JOIN","date":"2018-05-08T06:36:29.899Z","type":"message"}
{"nick":"Aquazi","date":"2018-05-08T06:38:16.402Z","type":"join"}
{"nick":"Jitu","reason":"Ping timeout: 260 seconds","date":"2018-05-08T06:43:44.996Z","type":"quit"}
{"nick":"samosaphile","date":"2018-05-08T07:33:14.451Z","type":"part"}
{"nick":"commma","message":"TrentonAdams: you can add always add an error handler","date":"2018-05-08T07:56:29.868Z","type":"message"}
{"nick":"puddle","date":"2018-05-08T08:46:42.598Z","type":"join"}
{"nick":"puddle","reason":"Client Quit","date":"2018-05-08T08:46:44.216Z","type":"quit"}
{"nick":"rorro","date":"2018-05-08T09:55:14.851Z","type":"join"}
{"nick":"mylesborins","reason":"Quit: farewell for now","date":"2018-05-08T10:25:08.194Z","type":"quit"}
{"nick":"rorro","reason":"Quit: Leaving","date":"2018-05-08T10:25:22.727Z","type":"quit"}
{"nick":"mylesborins","date":"2018-05-08T10:25:38.616Z","type":"join"}
{"nick":"popwinter","date":"2018-05-08T10:37:45.829Z","type":"join"}
{"nick":"popwinter","message":"https://pastebin.com/ZxCEZCwC Can anyone help me with this quick question of manipulating data?","date":"2018-05-08T10:38:00.233Z","type":"message"}
{"nick":"commma","message":"popwinter: this doesn't have anything to do with express. try ##javascript","date":"2018-05-08T11:00:53.312Z","type":"message"}
{"nick":"popwinter","message":"commma: It's okay. I think collections is the way to go. Anyway, is there any good reference material for unit testing in express?","date":"2018-05-08T11:01:36.213Z","type":"message"}
{"nick":"popwinter","message":"I would like to do unit testing for my APIs.","date":"2018-05-08T11:01:46.383Z","type":"message"}
{"nick":"Aquazi","reason":"Ping timeout: 260 seconds","date":"2018-05-08T11:04:39.528Z","type":"quit"}
{"nick":"rorro","date":"2018-05-08T11:23:54.473Z","type":"join"}
{"nick":"Aquazi","date":"2018-05-08T11:24:29.554Z","type":"join"}
{"nick":"sz0","reason":"Quit: Connection closed for inactivity","date":"2018-05-08T11:44:39.334Z","type":"quit"}
{"nick":"Aquazi","reason":"Ping timeout: 264 seconds","date":"2018-05-08T11:48:58.004Z","type":"quit"}
{"nick":"Aquazi","date":"2018-05-08T12:02:57.566Z","type":"join"}
{"nick":"Roughy","date":"2018-05-08T12:44:39.796Z","type":"join"}
{"nick":"Aquazi","reason":"Ping timeout: 260 seconds","date":"2018-05-08T12:45:34.552Z","type":"quit"}
{"nick":"TrentonAdams","message":"commma, I have error handlers.  Oh, maybe it's because it's happening within my error handler, lol.","date":"2018-05-08T13:10:21.026Z","type":"message"}
{"nick":"Aquazi","date":"2018-05-08T13:12:22.405Z","type":"join"}
{"nick":"commma","message":"TrentonAdams: not necessarily, some (awful) libraries consume errors themselves and rethrow them in such a way that the error handler can't catch","date":"2018-05-08T13:16:08.580Z","type":"message"}
{"nick":"commma","message":"in which case you need to use your `try`/`catch` method above to find them","date":"2018-05-08T13:16:18.955Z","type":"message"}
{"nick":"TrentonAdams","message":"commma, Node/javascript can be frustrating, lol.  javascript is such a loosy-goosy language.","date":"2018-05-08T13:18:46.262Z","type":"message"}
{"nick":"commma","message":"eh, i see these same problems in every other language i use other than haskell (which has its own set of problems)","date":"2018-05-08T13:20:02.301Z","type":"message"}
{"nick":"commma","message":"elixir, clojure, etc","date":"2018-05-08T13:20:10.218Z","type":"message"}
{"nick":"TrentonAdams","message":"commma, If I throw an exception from one express get request with function signature of function (req, res, next) my error handler never sees it.","date":"2018-05-08T13:20:33.597Z","type":"message"}
{"nick":"commma","message":"sounds like something else down the line is consuming the error before the handler sees it","date":"2018-05-08T13:21:12.847Z","type":"message"}
{"nick":"commma","message":"tbf, this is why `next(Error)` is a thing though!","date":"2018-05-08T13:21:35.325Z","type":"message"}
{"nick":"TrentonAdams","message":"What does tbf mean?","date":"2018-05-08T13:26:50.263Z","type":"message"}
{"nick":"TrentonAdams","message":"to be fair, right","date":"2018-05-08T13:27:26.131Z","type":"message"}
{"nick":"commma","message":"yes","date":"2018-05-08T13:36:39.314Z","type":"message"}
{"nick":"leolove","date":"2018-05-08T13:48:01.394Z","type":"join"}
{"nick":"leolove","reason":"Read error: Connection reset by peer","date":"2018-05-08T13:57:36.586Z","type":"quit"}
{"nick":"Aquazi_","date":"2018-05-08T14:03:37.812Z","type":"join"}
{"nick":"Arcarcarc","date":"2018-05-08T14:03:42.567Z","type":"join"}
{"nick":"Aquazi","reason":"Ping timeout: 260 seconds","date":"2018-05-08T14:06:04.589Z","type":"quit"}
{"nick":"Arcarc","reason":"Ping timeout: 260 seconds","date":"2018-05-08T14:06:04.802Z","type":"quit"}
{"nick":"Aquazi_","reason":"Quit: Leaving","date":"2018-05-08T14:19:59.411Z","type":"quit"}
{"nick":"Aquazi","date":"2018-05-08T14:20:17.448Z","type":"join"}
{"nick":"basiclaser","date":"2018-05-08T15:02:04.560Z","type":"join"}
{"nick":"rorro","reason":"Quit: Leaving","date":"2018-05-08T15:13:42.257Z","type":"quit"}
{"nick":"mven","date":"2018-05-08T15:39:09.988Z","type":"join"}
{"nick":"popwinter","reason":"Ping timeout: 264 seconds","date":"2018-05-08T15:46:33.976Z","type":"quit"}
