{"nick":"Roughy","reason":"Ping timeout: 268 seconds","date":"2018-05-08T00:50:19.802Z","type":"quit"}
{"nick":"Roughy","date":"2018-05-08T00:51:02.178Z","type":"join"}
{"nick":"leolove","reason":"Quit: This computer has gone to sleep","date":"2018-05-08T01:28:26.459Z","type":"quit"}
{"nick":"Roughy","reason":"Ping timeout: 264 seconds","date":"2018-05-08T01:31:33.968Z","type":"quit"}
{"nick":"Roughy","date":"2018-05-08T01:35:33.148Z","type":"join"}
{"nick":"Guest67487","date":"2018-05-08T02:07:10.385Z","type":"join"}
{"nick":"Guest67487","message":"So, I have a routine that throws an exception within an app.use(path, function(req, res, next){}) method.  is there a way of making that error appear, or do I have to wrap everything inside of the app.use with a try/catch to be sure it's not throwing an error that won't be seen?","date":"2018-05-08T02:08:24.520Z","type":"message"}
{"nick":"Guest67487","reason":"Quit: Leaving","date":"2018-05-08T02:30:08.623Z","type":"quit"}
{"nick":"TrentonAdams","date":"2018-05-08T02:30:38.183Z","type":"join"}
{"nick":"jgornick","reason":"Ping timeout: 240 seconds","date":"2018-05-08T03:05:51.418Z","type":"quit"}
{"nick":"Roughy","reason":"Quit: Meadow Fresh milk","date":"2018-05-08T03:21:46.020Z","type":"quit"}
{"nick":"Arcarc","date":"2018-05-08T03:43:11.474Z","type":"join"}
{"nick":"TrentonAdams","message":"I was in as guest earlier apparently.  So, I have a routine that throws an exception within an app.use(path, function(req, res, next){}) method.  is there a way of making that error appear, or do I have to wrap everything inside of the app.use with a try/catch to be sure it's not throwing an error that won't be seen?","date":"2018-05-08T03:43:17.409Z","type":"message"}
{"nick":"chovy","reason":"Quit: leaving","date":"2018-05-08T05:21:03.442Z","type":"quit"}
{"nick":"Jitu","date":"2018-05-08T06:34:48.965Z","type":"join"}
{"nick":"Jitu","message":"Hi","date":"2018-05-08T06:34:58.634Z","type":"message"}
{"nick":"Jitu","message":"what is path","date":"2018-05-08T06:35:17.464Z","type":"message"}
{"nick":"Jitu","message":"in nodejs","date":"2018-05-08T06:35:32.479Z","type":"message"}
{"nick":"Jitu","message":"JOIN","date":"2018-05-08T06:36:29.899Z","type":"message"}
{"nick":"Aquazi","date":"2018-05-08T06:38:16.402Z","type":"join"}
{"nick":"Jitu","reason":"Ping timeout: 260 seconds","date":"2018-05-08T06:43:44.996Z","type":"quit"}
{"nick":"samosaphile","date":"2018-05-08T07:33:14.451Z","type":"part"}
{"nick":"commma","message":"TrentonAdams: you can add always add an error handler","date":"2018-05-08T07:56:29.868Z","type":"message"}
