{"nick":"Guest72457","new_nick":"indutny","date":"2018-02-21T00:29:25.380Z","type":"nick"}
{"nick":"cm_","date":"2018-02-21T01:02:49.961Z","type":"join"}
{"nick":"cm_","message":"Hi. Is it a good place to ask technical questions about libuv?","date":"2018-02-21T01:03:45.032Z","type":"message"}
{"nick":"cm_","message":"it seems that internal new_socket() function can return positive error code -- it seems like a bug, but I'd like to confirm it before submitting it to issues list","date":"2018-02-21T01:07:08.735Z","type":"message"}
{"nick":"indutny","message":"hi","date":"2018-02-21T01:12:43.670Z","type":"message"}
{"nick":"indutny","message":"this is a good place, indeed","date":"2018-02-21T01:12:50.571Z","type":"message"}
{"nick":"indutny","message":"can it, though?","date":"2018-02-21T01:13:35.621Z","type":"message"}
{"nick":"AtumT","reason":"Remote host closed the connection","date":"2018-02-21T01:40:58.364Z","type":"quit"}
{"nick":"qard","reason":"Quit: My MacBook has gone to sleep. ZZZzzz…","date":"2018-02-21T01:49:28.948Z","type":"quit"}
{"nick":"qard","date":"2018-02-21T02:17:31.602Z","type":"join"}
{"nick":"qard","reason":"Quit: My MacBook has gone to sleep. ZZZzzz…","date":"2018-02-21T05:05:50.206Z","type":"quit"}
{"nick":"qard","date":"2018-02-21T05:51:12.696Z","type":"join"}
{"nick":"qard","reason":"Quit: qard","date":"2018-02-21T07:55:58.285Z","type":"quit"}
{"nick":"paolof","reason":"Ping timeout: 276 seconds","date":"2018-02-21T09:49:47.863Z","type":"quit"}
{"nick":"paolof_","date":"2018-02-21T09:49:48.785Z","type":"join"}
{"nick":"abhishek","date":"2018-02-21T11:08:04.449Z","type":"join"}
{"nick":"abhishek","message":"Hi, trying to debug one case where uv_write isn't invoking uv_write_cb callback - running on libuv v1.13.1 debian9","date":"2018-02-21T11:11:11.950Z","type":"message"}
{"nick":"abhishek","message":"any suggestion(s) to debug it? Weird thing is this only seems to happen under load i.e. works fine when app does 1K or so uv_write call/s but with 10K such calls triggering of uv_write_cb stalls","date":"2018-02-21T11:12:33.078Z","type":"message"}
{"nick":"AtumT","date":"2018-02-21T11:17:00.889Z","type":"join"}
{"nick":"mylesborins","reason":"Quit: farewell for now","date":"2018-02-21T11:25:11.437Z","type":"quit"}
{"nick":"mylesborins","date":"2018-02-21T11:25:47.411Z","type":"join"}
{"nick":"sgimeno","message":"abhishek, that version is quite old, you could update to the latest 1.19.1","date":"2018-02-21T12:13:45.987Z","type":"message"}
{"nick":"sgimeno","message":"abhishek, can you reproduce the issue when running the program with strace? that can help trying to figure out what's going on","date":"2018-02-21T12:14:29.413Z","type":"message"}
{"nick":"abhishek","reason":"Ping timeout: 240 seconds","date":"2018-02-21T12:16:05.447Z","type":"quit"}
{"nick":"Fishrock123","date":"2018-02-21T15:36:34.408Z","type":"join"}
{"nick":"qard","date":"2018-02-21T15:59:11.486Z","type":"join"}
